use_frameworks!

platform :ios, '9.0'

target 'OTJAlertController_Example' do
  pod 'OTJAlertController', :path => '../'

  target 'OTJAlertController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
